keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - FUTURE
lists:
  - name: What's Due?
    hidden: true
    ignore: false
    filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    id: 0
  - name: FUTURE
    hidden: false
    ignore: false
  - name: NOTE
    hidden: false
    ignore: false
  - name: TODO
    hidden: false
    ignore: false
  - name: DOING
    hidden: false
    ignore: false
  - name: DONE
    hidden: false
    ignore: true
  - name: Recently Completed
    hidden: false
    ignore: false
    filter: 'completedDate > "${14 days ago}" -completed'
    id: 1
settings:
  journalType: Folder
  journalPath: imdone-tasks
  taskPrefix: '#'
  maxLines: 6
  addNewCardsToTop: true
  newCardSyntax: MARKDOWN
  cards:
    colors: []
    computed:
      date: '${(new Date()).toDateString()}'
      time: '${(new Date()).toLocaleTimeString()}'
      timestamp: '${(new Date()).toISOString()}'
      sourceLink: '[${source.path}:${line}](${source.path}:${line})'
      dueEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const due = this.totals["What's Due?"]
          let emoji = ':2nd_place_medal:'
          if (due >= 3) {
            emoji = ':fire:'
          } else if (due === 0) {
            emoji = ':rocket:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
      recentEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const recentlyCompleted = this.totals["Recently Completed"]
          let emoji = ':2nd_place_medal:'
          if (recentlyCompleted >= 3) {
            emoji = ':rocket:'
          } else if (recentlyCompleted === 0) {
            emoji = ':fire:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
      wipEmoji: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        const doing = this.totals["DOING"]
          let emoji = ':2nd_place_medal:'
          if (doing >= 3) {
            emoji = ':fire:'
          } else if (doing === 0) {
            emoji = ':sleeping:'
          } else if (doing === 1) {
            emoji = ':rocket:'
          }
          return `<span style="font-size: 1.5em;">${emoji}</span>`
        }
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: twitter
        pack: fab
        title: Tweet this card
    trackChanges: true
    metaNewLine: true
  doneList: DONE
  filteredLists:
    - filter: 'due < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
      name: What's Due?
    - filter: 'completedDate > "${7 days ago}" -completed'
      name: Recently Completed
  journalTemplate: null
  openIn: default
  customOpenIn: !<tag:yaml.org,2002:js/undefined> ''
  editorTheme: blackboard
  replaceSpacesWith: '-'
  appendNewCardsTo: !<tag:yaml.org,2002:js/undefined> ''
